### ISSUE TITLE
Don't commit docs

### ISSUE THREAD

**Issue by samhh** [samhh/fp-ts-std#146]
Ideally they're generated. This'll mean cleaning up and exposing tshm-docs-ts.

**Comment by samhh** [comment]
tshm-docs-ts is in the Nix shell as of https://github.com/samhh/fp-ts-std/commit/34754889a78ff402ad328e85909cc5df73ed864c.

**Comment by samhh** [comment]
GitHub now supports deploying docs via Actions. Rough example of how this could look:

```yaml
on:
  push:
    branches:
      - master

jobs:
  docs:
    name: Publish docs
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      pages: write
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v21
      - run: nix develop -c yarn run docs
      - uses: actions/upload-pages-artifact@v1
        with:
          path: ./docs/
      - uses: actions/deploy-pages@v2
```

The tshm-docs-ts Nix derivation will probably need a little bit of fiddling first.

It's still useful to generate the docs during dev, so `:/docs/` would need adding to `.gitignore`.
